on:
  schedule:
    - cron: '0 13 * * *' # UTC time, runs at 08:00 UTC (16:00 Beijing Time)
  # Optionally, you can add other events like push or workflow_dispatch here if needed.

jobs:
  auto-sign-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use the latest Python 3 version

      - name: Run Auto Sign-in Script
        env:
          # If your script needs environment variables (like API keys), set them here.
          cookie: ${{ secrets.COOKIE }}
        run: |
          python cg163-autocheckin.py

      # 如果您想要测试使用 Node20，请取消注释下面的行
      # - name: Force Actions to use Node20
      #   run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE20=true" >> $GITHUB_ENV
